name = "fabirc"
author = "natgo"
version = "1.19.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7db39019ebfcd0b4a6113602f7e741b0fb9aa0d22e410e0313ad008e6a39edba"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
