name = "fabirc"
author = "natgo"
version = "1.8.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2eef6b6d23aea0c783ce516f0256e1ab0150897890669a567d513abb097ed2f1"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
