name = "fabirc"
author = "natgo"
version = "1.8.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca46e1027e1e48735b8076458af6b1969d75a3faf562c423d0b2844422b0af90"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
