name = "fabirc"
author = "natgo"
version = "1.8.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8087645503d60220997d29db22e39db263c00fe198b8861f8113e4dc8c522e7"

[versions]
fabric = "0.14.2"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
