name = "fabirc"
author = "natgo"
version = "1.8.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56dc1fa65befaf6c2336bd6f50b9f34088d34e8e16020a7ca1e5aad6d03e83b0"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
