name = "fabirc"
author = "natgo"
version = "1.8.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7480c426c4543651f70fc0b2af615676267fe42d28d3f51bfd537709d46214b2"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
