name = "fabirc"
author = "natgo"
version = "1.8.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3401b98fe350e2c565e591d2ff4fe3f8380dd04cdcdf20e10762cc365a2a0d0b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
