name = "fabirc"
author = "natgo"
version = "1.8.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad3400cbb5b666488e269a43eb2ca23c8b5aed16215d638b57d58c4924492f88"

[versions]
fabric = "0.14.2"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
