name = "fabirc"
author = "natgo"
version = "1.18.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af14ca4af18e3a6a42ec6a8d869b953f2cbe6d2bd8f1ff823ba9401cc14a8f20"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
